config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

#admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # Gallery urls
    url(r'^gallery/', include("fluidbuntu.gallery.urls", namespace="gallery")),

    # User management
    url(r'^users/', include("fluidbuntu.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

fluidbuntu/gallery/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.index,
        name='index'
    ),
    # Author list
    url(
        regex=r'^authors/$',
        view=views.author_list,
        name='author_list'
    ),

    # filter by author URL
    url(
        regex=r'^author/(?P<slug>[-\w\d]+)-(?P<id>\d+)/$',
        view=views.author,
        name='author'
    ),

    # filter by date
    url(
        regex=r'^date',
        view=views.date,
        name='date'
    ),
    url(
        regex=r'^(?P<date_range>20\d{2}(/\d{1,2})?(/\d{1,2})?)$',
        view=views.date_range,
        name='date_range'
    ),


    url(
        regex=r'^pic/(?P<uslug>[-\w\d]+)-(?P<id>[\d_]+)/$',
        view=views.single_photo,
        name='single_photo'
    ),

]

fluidbuntu/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

fluidbuntu/gallery/models.py
from __future__ import unicode_literals
import logging
from unidecode import unidecode  # Used to slugify usernames

from django.db import models
from django.dispatch import receiver
from django.utils.text import slugify
from django.core.urlresolvers import reverse
# from django.db.models import

from .utils.scanforum import scan_forum, get_page
from .utils.managephotos import \
    get_photo_files, EXIF_TAG_NAMES, EXIF_TAGS, EXIF_DATA_TYPE
#    set_upload_path_lr
from datetime import datetime
from urllib2 import HTTPError

logger = logging.getLogger(__name__)
FORUM_BASE_URL = 'https://forum.ubuntu-fr.org/viewtopic.php?pid='

PHOTO_SIZES = {
    'LR': 640,  # Width or Height for the small image
    'HR': 2000,  # Max Width or Height for the large image
}


def set_photo_path(instance, filename):
    """
    :type instance: Photo
    :type filename: str
    :rtype: str
    """
    try:
        photo_date = instance.post_date
    except:
        photo_date = datetime.now()
    path = 'photo/{0}/{1:02d}/'.format(photo_date.year,
                                       photo_date.month) + filename
    return path


# Methods kept for backward compatibility
# To be removed after having squashed migrations
def set_upload_path_hr(instance, filename):
    return set_photo_path(instance, filename)


def set_upload_path_lr(instance, filename):
    return set_photo_path(instance, filename)


class User(models.Model):
    forum_id = models.IntegerField(null=True)  # forum user id
    name = models.CharField(max_length=255)

    def get_absolute_url(self):
        return reverse('gallery:author', kwargs={
            'slug': self.slug(),
            'id': str(self.id)})

    def slug(self):
        return slugify(unidecode(self.name))

    def _is_used(self):
        """
        Checks if user has related photos.
        :rtype: bool
        """
        return Photo.objects.filter(author=self).exists()

    is_used = property(_is_used)

    objects = models.Manager

    def __str__(self):
        return unicode(self.name).encode('utf-8')


class Unit(models.Model):
    name = models.CharField(max_length=63)
    symbol = models.CharField(max_length=20)


class Attribute(models.Model):
    DATA_TYPE_CHOICES = (
        (0, 'Short text (<255 characters)'),
        (1, 'Long text'),
        (2, 'Point (float) value'),
        (3, 'Date time'),
    )

    name = models.CharField(max_length=255)
    attribute_type = models.IntegerField(choices=DATA_TYPE_CHOICES)
    unit = models.ForeignKey(Unit, null=True)

    def __str__(self):
        return self.name


class Layout(models.Model):
    name = models.CharField(max_length=255)
    attributes = models.ManyToManyField(
        Attribute,
        through='LayoutItems',
        through_fields=('layout', 'attribute'),
    )


class LayoutItems(models.Model):
    attribute = models.ForeignKey(Attribute, on_delete=models.CASCADE)
    layout = models.ForeignKey(Layout, on_delete=models.CASCADE)

    order = models.IntegerField()


class Data(models.Model):
    attribute = models.ForeignKey(Attribute)
    # photo = models.ForeignKey('Photo')
    shorttxt = models.CharField(max_length=255)
    longtxt = models.TextField()
    point = models.FloatField()
    datetime = models.DateTimeField()


class Manufacturer(models.Model):
    name = models.CharField(max_length=255)

    @property
    def is_used(self):
        """
        Checks if user has related photos.
        :rtype: bool
        """
        return not Camera.objects.filter(manufacturer=self).exists()

    def __str__(self):
        return self.name


class Camera(models.Model):
    name = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, related_name='camera_set')

    @property
    def is_used(self):
        """
        Checks if user has related photos.
        :rtype: bool
        """
        return not Photo.objects.filter(camera=self).exists()

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=255)
    # How to enforce uniqueness within a branch?
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class Photo(models.Model):
    # SIZE_LARGE = 2000  # Max Width or Height for the large image
    # SIZE_SMALL = 640  # Width or Height for the small image

    id = models.CharField(max_length=255, primary_key=True)
    # ID generated at import
    post_id = models.IntegerField()
    author = models.ForeignKey(User, related_name='photo_set')
    camera = models.ForeignKey(Camera, null=True, blank=True,
                               related_name='photo_set')
    # Add links to TAGS - should be a many to many relation
    post_date = models.DateTimeField(null=True, blank=True)
    photo_date = models.DateTimeField(null=True, blank=True)
    added_date = models.DateTimeField(auto_now_add=True, blank=True)

    photo_low_res = models.ImageField(max_length=255, blank=True,
                                      upload_to=set_photo_path)
    photo_high_res = models.ImageField(max_length=255, blank=True,
                                       upload_to=set_photo_path)
    # post_id = models.IntegerField #Ubuntu ID - check if integer is OK

    tags = models.ManyToManyField(Tag, blank=True)
    technical_details = models.ManyToManyField(Data, blank=True)

    topic = models.ForeignKey('Topic', null=True)

    def get_absolute_url(self):
        return reverse('gallery:single_photo', kwargs={
            'uslug': self.author.slug(),
            'id':self.id,
        })

    # @property
    # def slug(self):
    #     return slugify(unidecode(self.author.name + "_" + self.id))
        # return self.author.slug() + unidecode("_" + id)

    def _get_post_url(self):
        return '{0}{1}#p{1}'.format(FORUM_BASE_URL, self.post_id)

    post_url = property(_get_post_url)

    # Check for different field type
    # Full URL or reconstruct from ID and user preference (u|ku|xu)

    # Technical attributes

    def add_author(self, username):
        user, created = User.objects.get_or_create(name=username)
        if created:
            user.save()
        self.author = user

    def __str__(self):
        return self.post_url

    def process_exif(self, exif):
        """
        Add exif to
        :param exif:
        :type exif: dict
        :return:
        """
        if exif[EXIF_TAG_NAMES.Make] and exif[EXIF_TAG_NAMES.Model]:
            make, created = Manufacturer.objects.get_or_create(
                name=exif[EXIF_TAG_NAMES.Make])
            if created:
                make.save()

            model = Camera.objects.get_or_create(name=exif[
                EXIF_TAG_NAMES.Model], manufacturer=make)
            if created:
                model.manufacturer = make
                model.save()

        for key in exif:
            if not (key == EXIF_TAG_NAMES.Make or key == EXIF_TAG_NAMES.Model):
                self.add_data(key, EXIF_TAGS[key]['type'], exif[key])

    def add_data(self, attribute_name, attribute_type, datum):
        attribute, created = Attribute.objects.get_or_create(
            name=attribute_name)
        if created:
            attribute.attribute_type = attribute_type
            attribute.save()
        d = Data()
        d.attribute = attribute
        if attribute_type == EXIF_DATA_TYPE.Short_text:
            d.shorttxt = str(datum)
        elif attribute_type == EXIF_DATA_TYPE.Long_text:
            d.longtxt = str(datum)
        elif attribute_type == EXIF_DATA_TYPE.Point:
            d.point = float(datum) #Todo: add error handling
        elif attribute_type == EXIF_DATA_TYPE.DateTime:
            d.datetime == datum #Todo: add date checker
        else:
            raise ValueError
        d.save()
        self.technical_details.add(d)



class Topic(models.Model):
    post_id = models.IntegerField()
    name = models.CharField(null=True, max_length=255)
    last_import_date = models.DateTimeField(null=True, auto_now=True)
    last_post_id_imported = models.IntegerField(null=True, blank=True)

    def _get_topic_url(self):
        return '%s%s' % (FORUM_BASE_URL, self.post_id)

    topic_url = property(_get_topic_url)

    def _get_last_imported_url(self):
        if self.last_post_id_imported:
            return '%s%s' % (FORUM_BASE_URL, self.last_post_id_imported)
        else:
            return None

    last_imported_url = property(_get_last_imported_url)

    def run_import(self):
        logger.info('Start import...')
        previous_import = self.last_imported_url
        if previous_import:
            last_post_url = previous_import
            is_new_topic = False
            logger.info('Updating existing topic')
        else:
            last_post_url = self.topic_url
            is_new_topic = True
            logger.info('New topic.')

        photo_collection = []
        try:
            photo_collection = scan_forum(last_post_url, is_new_topic)
        except HTTPError as inst:
            if inst.code == 404:
                self.clean_photos()
                logger.warning('Invalid photo removed. Scan aborted.')
                return None

        logger.info('{0} topics fetched.'.format(len(photo_collection)))
        self.import_photos(photo_collection)
        self.last_post_id_imported = photo_collection[-1]['id']
        self.save()

    def import_photos(self, photo_collection):
        for post in photo_collection:
            if not Photo.objects.filter(post_id=post['id']).exists():
                for index, photo in enumerate(post['photos']):
                    # sizes = [Photo.SIZE_SMALL, Photo.SIZE_LARGE]
                    photo_id = '{0}_{1}'.format(post['id'], str(index))
                    try:
                        photo_files, exif_data = \
                            get_photo_files(photo_id, photo['url'],
                                            photo['link_url'], PHOTO_SIZES)

fluidbuntu/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

fluidbuntu/gallery/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader
# from django.core.paginator import Paginator, InvalidPage
from django.core import serializers
from el_pagination.decorators import page_template
from utils.misc import assess_date_range

from .models import Photo, User
# , User, Unit, Attribute, Layout, LayoutItems, Data, Manufacturer, Camera, Tag


# Create your views here.
@page_template('gallery/entry_list_page.html')  # just add this decorator
def index(request, template='gallery/index.html', extra_context=None):
    context = {
        'photo_list': Photo.objects.all().order_by('-added_date').select_related('author', 'camera__manufacturer'),
        'user_list': User.objects.all().order_by('name'),
        # 'page': page_photo,
    }

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


@page_template('gallery/entry_list_page.html')  # just add this decorator
def author(request, slug, id, template='gallery/index.html', \
                                     extra_context=None):
    author = get_object_or_404(User, pk=id)

    context = {
        'photo_list': Photo.objects.all().filter(author_id=id).order_by(
            '-added_date').select_related('author', 'camera__manufacturer'),
        'user_list': User.objects.all(),
        'author': author,
    }
    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


def author_list(request, template='gallery/authors.html', extra_context=None):
    context = {
        'author_list': User.objects.all().order_by('name'),
    }

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


def date(request, template='gallery/date.html', extra_context=None):
    context = {
        'photo_list': Photo.objects.all().order_by('post_date'),
    }

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)

@page_template('gallery/entry_list_page.html')
def date_range(request, date_range, template='gallery/index.html', \
               extra_context=None):
    try:
        start_date, end_date = assess_date_range(date_range)
    except ValueError:
        raise Http404('Date range not valid.')

    context = {
        'photo_list': Photo.objects.all().filter(
            post_date__range=[start_date, end_date])
            .order_by('post_date').select_related('author',
                                                  'camera__manufacturer'),
        'user_list': User.objects.all().order_by('name'),
        }

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


@page_template('gallery/entry_list_page.html')  # just add this decorator
def single_photo(request, uslug, id, template='gallery/index.html', \
                                      extra_context=None):
    photo = get_object_or_404(
        Photo.objects.select_related('author', 'camera__manufacturer'), id=id)
    context = {
        'photo_list': [photo,],
        'user_list': User.objects.all(),
    }

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)

fluidbuntu/templates/gallery/authors.html
{% extends "gallery/base.html" %}
{% load staticfiles i18n %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_title %}
  {{ block.super }} | Authors
{% endblock bootstrap3_title%}



{% block content %}
{% for a in author_list %}
   {% if forloop.counter0|divisibleby:3 and not forloop.first %}
  </div>
  {% endif %}
  {% if forloop.counter0|divisibleby:3 %}
  <div class="row">
  {% endif %}
            <div class="author col-md-3">
                <p><a href="{{a.get_absolute_url}}">{{a.name}}</a></p>
                <p class="author-note">{{a.photo_set.count}}</p>
            </div>
   {% if forloop.last %}
  </div>
  {% endif %}

{% endfor %}
{% endblock content%}

{% block bootstrap3_extra_script %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}el-pagination/js/el-pagination.js"></script>
    <script>$.endlessPaginate({paginateOnScroll: true});</script>

    <script>
      function submituser() {
        location.href = author.value
      }
    </script>
{% endblock bootstrap3_extra_script %}

fluidbuntu/templates/gallery/base.html
{% extends "base.html" %}

fluidbuntu/templates/gallery/date.html
{% extends "gallery/base.html" %}
{% load staticfiles i18n %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_title %}
  {{ block.super }} | Authors
{% endblock bootstrap3_title%}



{% block content %}
{% regroup photo_list by post_date|date:"Y" as photo_years %}


  {% for y in photo_years %}
  <h2> {{ y.grouper }} <h2/>
  {% regroup y.list by post_date|date:"m" as photo_months %}

    <p>
    {% for m in photo_months %}
    {% if not forloop.first %} | {% endif %}
      {% with forloop.counter0 as position %}
      {{m.grouper}} :
      {% endwith %}
      <a href="{{y.grouper}}/{{m.grouper}}">{{m.list|length}}</a>
    {% endfor %}
    </p>

  {% endfor %}


{% endblock content%}

fluidbuntu/templates/gallery/entry_list_page.html
{% load el_pagination_tags %}

{% paginate 3 photo_list %}

{% for p in photo_list %}
       <div class="photo-block row" id='{{p.id}}'>
            <div class="photo col-md-9">
                <img src='{{p.photo_low_res.url}}' alt='{{ p.id }}'/>
            </div>
            <div class="photo-side col-md-3">
              <div class="permalink">
                <a href="{{p.get_absolute_url}}">#{{forloop.counter}}</a>
              </div>
              <div class="photo-author">
                <a href="{{p.post_url}}"> posted on {{p.post_date|date:"D d M Y" }}</a>, by
                 <a href="{{p.author.get_absolute_url}}">{{p.author.name}}</a>
              </div>
              <div class="photo-attributes">
                <!-- to be implemented -->
              </div>
            </div>
        </div>
{% endfor %}
{% show_more %}

fluidbuntu/templates/gallery/index.html
{% extends "gallery/base.html" %}
{% load staticfiles i18n %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_title %}{{ block.super }}
{% if "author" in request.path %}
 | {{author.name}}'s photos
{% endif %}
{% endblock bootstrap3_title%}


{% block menubar_extra %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'gallery:date' %}">Date</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'gallery:author_list' %}">Authors</a>
  </li>
  <!--<li class="nav-item">
    <form name="userform" onsubmit="return submituser();">
      <input type="text" id="author" name="author" list="authors-list"
             placeholder="e.g. jeange">
      <input type="submit" value="OK">
    </form>
  </li>-->

<datalist id="authors-list">
  {% for u in user_list %}
    <option value='{{u.get_absolute_url}}'>{{u.name}}</option>
  {% endfor %}
  </datalist>
{% endblock menubar_extra %}

{% block content %}
{% if photo_list %}
    {% include page_template %}
{% else %}
    <p>No photo available</p>
{% endif %}

{% endblock content%}

{% block bootstrap3_extra_script %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}el-pagination/js/el-pagination.js"></script>
    <script>$.endlessPaginate({paginateOnScroll: true});</script>

    <script>
      function submituser() {
        location.href = author.value
      }
    </script>
{% endblock bootstrap3_extra_script %}