config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

#admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # Gallery urls
    url(r'^gallery/', include("fluidbuntu.gallery.urls", namespace="gallery")),

    # User management
    url(r'^users/', include("fluidbuntu.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

fluidbuntu/gallery/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.index,
        name='index'
    ),
    # Author list
    url(
        regex=r'^authors/$',
        view=views.author_list,
        name='author_list'
    ),

    # filter by author URL
    url(
        regex=r'^author/(?P<slug>[-\w\d]+)-(?P<id>\d+)/$',
        view=views.author,
        name='author'
    ),

    # filter by date
    url(
        regex=r'^date',
        view=views.date,
        name='date'
    ),
    url(
        regex=r'^(?P<date_range>20\d{2}(/\d{1,2})?(/\d{1,2})?)$',
        view=views.date_range,
        name='date_range'
    ),


    url(
        regex=r'^pic/(?P<uslug>[-\w\d]+)-(?P<id>[\d_]+)/$',
        view=views.single_photo,
        name='single_photo'
    ),

]

fluidbuntu/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

fluidbuntu/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of User"), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

fluidbuntu/gallery/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, Http404
from django.template import loader
# from django.core.paginator import Paginator, InvalidPage
from django.core import serializers
from el_pagination.decorators import page_template
from utils.misc import assess_date_range

from .models import Photo, User
# , User, Unit, Attribute, Layout, LayoutItems, Data, Manufacturer, Camera, Tag


# Create your views here.
@page_template('gallery/entry_list_page.html')  # just add this decorator
def index(request, template='gallery/index.html', extra_context=None):
    context = {
        'photo_list': Photo.objects.all().order_by('-added_date').select_related('author', 'camera__manufacturer'),
        'user_list': User.objects.all().order_by('name'),
        # 'page': page_photo,
    }

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


@page_template('gallery/entry_list_page.html')  # just add this decorator
def author(request, slug, id, template='gallery/index.html', \
                                     extra_context=None):
    author = get_object_or_404(User, pk=id)

    context = {
        'photo_list': Photo.objects.all().filter(author_id=id).order_by(
            '-added_date').select_related('author', 'camera__manufacturer'),
        'user_list': User.objects.all(),
        'author': author,
    }
    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


def author_list(request, template='gallery/authors.html', extra_context=None):
    context = {
        'author_list': User.objects.all().order_by('name'),
    }

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


def date(request, template='gallery/date.html', extra_context=None):
    context = {
        'photo_list': Photo.objects.all().order_by('post_date'),
    }

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)

@page_template('gallery/entry_list_page.html')
def date_range(request, date_range, template='gallery/index.html', \
               extra_context=None):
    try:
        start_date, end_date = assess_date_range(date_range)
    except ValueError:
        raise Http404('Date range not valid.')

    context = {
        'photo_list': Photo.objects.all().filter(
            post_date__range=[start_date, end_date])
            .order_by('post_date').select_related('author',
                                                  'camera__manufacturer'),
        'user_list': User.objects.all().order_by('name'),
        }

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)


@page_template('gallery/entry_list_page.html')  # just add this decorator
def single_photo(request, uslug, id, template='gallery/index.html', \
                                      extra_context=None):
    photo = get_object_or_404(
        Photo.objects.select_related('author', 'camera__manufacturer'), id=id)
    context = {
        'photo_list': [photo,],
        'user_list': User.objects.all(),
    }

    if extra_context is not None:
        context.update(extra_context)
    return render(request, template, context)

fluidbuntu/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

fluidbuntu/templates/base-old.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}fluidbuntu{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="{% static 'bower_components/html5shiv/dist/html5shiv.min.js' %}
"></script>
    <![endif]-->

    {% block css %}

    <!-- Your stuff: Third-party css libraries go here -->

    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    {% block angular %}
    <script src="{% static 'bower_components/angular/angular.min.js' %}"></script>
    {% endblock %}

  </head>

  <body>

    <div class="m-b">
      <nav class="navbar navbar-dark navbar-static-top bg-inverse">
        <div class="container">
          <a class="navbar-brand" href="/">fluidbuntu</a>
          <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            &#9776;
          </button>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
            </ul>

            <ul class="nav navbar-nav pull-xs-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> -->


      <!-- Tether - a requirement for Bootstrap tooltips -->
      <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>-->

      <!-- Latest compiled and minified JavaScript -->
      <!-- <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>-->

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>

fluidbuntu/templates/base.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% load staticfiles i18n %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_title %}Fluidbuntu{% endblock bootstrap3_title%}



{% block bootstrap3_extra_head %}
  <link href="{% static 'css/project.css' %}" rel="stylesheet">
  {% block angular %}
  <!-- <script
  src="{% static 'bower_components/angular/angular.min.js' %}"></script>-->
  {% endblock angular %}
{% endblock bootstrap3_extra_head%}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block bootstrap3_content %}
    <div class="m-b">
      <nav class="navbar navbar-inverse navbar-static-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">fluidbuntu</a>
          </div>


          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'gallery:index' %}">Home</a>
              </li>
<!--
              <li class="nav-item">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
-->
            </ul>
            <ul class="nav navbar-nav navbar-right">
              {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Logout" %}</a>
                </li>
              {% else %}
                <!-- <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Log In" %}</a>
                </li>-->
              {% endif %}
              {% block menubar_extra %}
              {% endblock menubar_extra %}
            </ul>
          </div>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}
    </div> <!-- /container -->
{% endblock bootstrap3_content %}

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block bootstrap3_extra_script %}
      <!-- Latest JQuery -->
      <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> -->


      <!-- Tether - a requirement for Bootstrap tooltips -->
      <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>-->

      <!-- Latest compiled and minified JavaScript -->
      <!-- <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>-->

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock bootstrap3_extra_script %}